### ISSUE TITLE
Has missing files and not working

### ISSUE THREAD

**Issue by drtzack** [calendee/ionic-leafletjs-map-demo#3]
<script src="js/controllers/appController.js"></script>
there is no file "appController.js" and also 

Error: [$parse:syntax] http://errors.angularjs.org/1.3.13/$parse/syntax?p0=.0&p1=is%20an%20unexpected%20token&p2=8&p3=markers.0&p4=.0
    at Error (native)
    at http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:37:417
    at ib.throwError (http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:221:165)
    at ib.parse (http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:219:499)
    at $get (http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:141:201)
    at l.$get.l.$watch (http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:150:332)
    at angular.module.factory.addMarkerWatcher (http://192.168.1.30:8100/lib/leaflet/angular-leaflet-directive.min.js:32:18967)
    at Object.fn (http://192.168.1.30:8100/lib/leaflet/angular-leaflet-directive.min.js:31:12664)
    at l.$get.l.$digest (http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:154:138)
    at l.$get.l.$apply (http://192.168.1.30:8100/lib/ionic/js/ionic.bundle.js:157:58)

It can't find my location. It works on pc browser well.

**Comment by calendee** [comment]
Thanks for pointing that appController file out.  It was left over from another demo.

I've fixed the parse error as well by updating the angular-leaflet directive.

You should now be able to get your location on mobile as well.  Make sure you are including the step to add the geolocation plugin in the instructions.

**Comment by drtzack** [comment]
Thank you for commit. Errors are gone. But still it can't locate.
It's not asking for enable GPS or something. I manually activated but still doesn't work.

**Comment by calendee** [comment]
Are you doing this step? : `cordova plugin add org.apache.cordova.geolocation`

**Comment by drtzack** [comment]
Yes. I did and tested it different devices and computers. It's still same.

**Comment by calendee** [comment]
Then, I'd suggest you install [GapDebug](https://www.genuitec.com/products/gapdebug/) and inspect it for any errors.

I'd also suggest you try building again and then running in Xcode
`cordova build ios`

**Comment by drtzack** [comment]
I have no IOS device only android. I made a debug for geolocation module.

navigator.geolocation.getCurrentPosition(function(x){console.log(x)},function(x){console.log(x)},{ enableHighAccuracy: true, timeout: 2*1000, maximumAge: 0 })
PositionError {message: "Timeout expired", code: 3, PERMISSION_DENIED: 1, POSITION_UNAVAILABLE: 2, TIMEOUT: 3}
